// src/components/DrawingScreen.tsx
import React, {
  useEffect,
  useState,
  useCallback,
  useLayoutEffect,
  useRef,
  MouseEvent,
  WheelEvent
} from 'react'
import { ToolBar } from './ToolBar'
import { DrawingService } from '../services/DrawingService'
import { useParams, useHistory } from 'react-router-dom'
import styled from '@emotion/styled'
import { Point } from '../services/PictureService'
import { Tool } from '../types/Tool'

type Props = {}

export function DrawingScreen({}: Props) {
  const drawingService = DrawingService.instantiate()
  const { pictureId } = useParams()
  const history = useHistory()

  const [paths, setPaths] = useState(drawingService.picture?.paths)

  const [selectedTool, setSelectedTool] = useState('pen' as Tool)
  const [palmRejectionEnabled, setPalmRejectionEnabled] = useState(false)

  const [offset, setOffset] = useState<[number, number]>([0, 0])

  const internals = useRef({
    prevX: 0,
    prevY: 0,
    drawTicking: false,
    scrollTicking: false,
    offsetX: 0,
    offsetY: 0,
    handScrollingByMouse: false,
    svgElementOffset: [0, 0] as [number, number]
  }).current

  const svgRef = useRef<SVGSVGElement>(null)
  const svgWrapperRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    drawingService.clean()

    if (typeof pictureId === 'string') {
      drawingService.loadPicture(pictureId).then(() => {
        // titleAdapterService.title.next(this.title)
        setPaths(drawingService.picture?.paths)
      })
    } else {
      drawingService.init()
      setPaths(drawingService.picture?.paths)
      // titleAdapterService.title.next(this.title)
    }

    return drawingService.onSave.subscribe(({ pictureId: newPictureId }) => {
      if (newPictureId !== pictureId) {
        history.push(`/${newPictureId}`)
      }
    })
  }, [pictureId])

  const tickDraw = useCallback(() => {
    if (internals.drawTicking) return

    internals.drawTicking = true
    requestAnimationFrame(() => {
      setPaths(drawingService.picture?.paths)
      internals.drawTicking = false
    })
  }, [internals])

  const tickScroll = useCallback(() => {
    if (internals.scrollTicking) return

    internals.scrollTicking = true
    requestAnimationFrame(() => {
      setOffset([internals.offsetX, internals.offsetY])
      internals.scrollTicking = false
    })
  }, [internals])

  const onWheel = useCallback(
    (event: WheelEvent) => {
      internals.offsetX += event.deltaX
      internals.offsetY += event.deltaY

      tickScroll()
    },
    [internals]
  )

  const onMouseDown = useCallback(
    (event: React.MouseEvent) => {
      const { left, top } = svgRef.current!.getBoundingClientRect()
      internals.svgElementOffset = [left, top]

      switch (selectedTool) {
        case 'pen':
          drawingService.handlePenDown({
            color: '#000',
            width: 3,
            ...getXYFromMouseEvent(event, internals.svgElementOffset, offset)
          })
          tickDraw()
          break

        case 'eraser':
          drawingService.handleEraserDown(
            getXYFromMouseEvent(event, internals.svgElementOffset, offset)
          )
          tickDraw()
          break

        case 'hand': {
          const xy = getXYFromMouseEvent(event, internals.svgElementOffset)
          internals.prevX = xy.x
          internals.prevY = xy.y
          internals.handScrollingByMouse = true
          break
        }
      }
    },
    [drawingService, selectedTool, tickDraw, offset]
  )

  const onMouseMove = useCallback(
    (event: React.MouseEvent) => {
      switch (selectedTool) {
        case 'pen':
          drawingService.handlePenMove(
            getXYFromMouseEvent(event, internals.svgElementOffset, offset)
          )
          tickDraw()
          break

        case 'eraser':
          drawingService.handleEraserMove(
            getXYFromMouseEvent(event, internals.svgElementOffset, offset)
          )
          tickDraw()
          break

        case 'hand': {
          if (internals.handScrollingByMouse) {
            const xy = getXYFromMouseEvent(event, internals.svgElementOffset)
            internals.offsetX += internals.prevX - xy.x
            internals.offsetY += internals.prevY - xy.y
            internals.prevX = xy.x
            internals.prevY = xy.y
            tickScroll()
          }
          break
        }
      }
    },
    [selectedTool, drawingService, offset]
  )

  useLayoutEffect(() => {
    const onMouseUpGlobal = () => {
      switch (selectedTool) {
        case 'pen':
          drawingService.handlePenUp()
          break

        case 'eraser':
          drawingService.handleEraserUp()
          break

        case 'hand':
          internals.handScrollingByMouse = false
          break
      }
    }
    document.addEventListener('mouseup', onMouseUpGlobal)

    return () => {
      document.removeEventListener('mouseup', onMouseUpGlobal)
    }
  }, [selectedTool, drawingService, internals])

  useLayoutEffect(() => {
    const svg = svgRef.current
    if (svg == null) return

    const onTouchStart = (event: TouchEvent) => {
      const { left, top } = svgRef.current!.getBoundingClientRect()
      internals.svgElementOffset = [left, top]

      switch (selectedTool) {
        case 'pen': {
          const xy = getXYFromTouchEvent(
            event,
            internals.svgElementOffset,
            getTouchType(palmRejectionEnabled),
            offset
          )
          if (xy != null) {
            drawingService.handlePenDown({
              color: '#000',
              width: 3,
              ...xy
            })
            break
          }

          // fall through
        }

        case 'eraser': {
          const xy = getXYFromTouchEvent(
            event,
            internals.svgElementOffset,
            getTouchType(palmRejectionEnabled),
            offset
          )
          if (xy != null) {
            drawingService.handleEraserDown(xy)
            break
          }

          // fall through
        }

        default: {
          const xy = getXYFromTouchEvent(event, internals.svgElementOffset, null)
          if (xy == null) break
          internals.prevX = xy.x
          internals.prevY = xy.y
          break
        }
      }
    }

    const onTouchMove = (event: TouchEvent) => {
      switch (selectedTool) {
        case 'pen': {
          const xy = getXYFromTouchEvent(
            event,
            internals.svgElementOffset,
            getTouchType(palmRejectionEnabled),
            offset
          )
          if (xy != null) {
            drawingService.handlePenMove(xy)
            tickDraw()
            break
          }

          // fall through
        }

        case 'eraser': {
          const xy = getXYFromTouchEvent(
            event,
            internals.svgElementOffset,
            getTouchType(palmRejectionEnabled),
            offset
          )
          if (xy != null) {
            drawingService.handleEraserMove(xy)
            tickDraw()
            break
          }

          // fall through
        }

        default: {
          const xy = getXYFromTouchEvent(event, internals.svgElementOffset, null)
          if (xy == null) break
          internals.offsetX += internals.prevX - xy.x
          internals.offsetY += internals.prevY - xy.y
          internals.prevX = xy.x
          internals.prevY = xy.y

          tickScroll()
          break
        }
      }
    }

    const onTouchEnd = (event: TouchEvent) => {
      switch (selectedTool) {
        case 'pen': {
          const xy = getXYFromTouchEvent(
            event,
            internals.svgElementOffset,
            getTouchType(palmRejectionEnabled),
            offset
          )
          if (xy != null) {
            drawingService.handlePenMove(xy)
            drawingService.handlePenUp()
            tickDraw()
            break
          }

        // fall through
        }

        case 'eraser': {
          const xy = getXYFromTouchEvent(
            event,
            internals.svgElementOffset,
            getTouchType(palmRejectionEnabled),
            offset
          )
          if (xy != null) {
            drawingService.handleEraserMove(xy)
            drawingService.handleEraserUp()
            tickDraw()
            break
          }

        // fall through
        }

        default: {
          const xy = getXYFromTouchEvent(event, internals.svgElementOffset, null)
          if (xy == null) break
          internals.offsetX += internals.prevX - xy.x
          internals.offsetY += internals.prevY - xy.y
          internals.prevX = xy.x
          internals.prevY = xy.y

          tickScroll()
          break
        }
      }
    }

    svg.addEventListener('touchstart', onTouchStart, { passive: true })
    svg.addEventListener('touchmove', onTouchMove, { passive: true })
    svg.addEventListener('touchend', onTouchEnd, { passive: true })

    return () => {
      svg.removeEventListener('touchstart', onTouchStart)
      svg.removeEventListener('touchmove', onTouchMove)
      svg.removeEventListener('touchend', onTouchEnd)
    }
  }, [
    internals,
    palmRejectionEnabled,
    drawingService,
    tickDraw,
    tickScroll,
    svgRef,
    offset,
    selectedTool
  ])

  return (
    <Container>
      <ToolBar
        title="Untitled"
        onTitleChange={() => {}}
        selectedTool={selectedTool}
        onSelectedToolChange={setSelectedTool}
        palmRejectionEnabled={palmRejectionEnabled}
        onPalmRejectionEnabledChange={setPalmRejectionEnabled}
      />
      <div ref={svgWrapperRef} className="svg-wrapper">
        <svg ref={svgRef} onWheel={onWheel} onMouseDown={onMouseDown} onMouseMove={onMouseMove}>
          {paths?.map(({ points, color, width }, i) => (
            <path
              key={i}
              fill="none"
              stroke={color}
              strokeWidth={width}
              d={points
                .map(({ x, y }, i) => {
                  if (i === 0) {
                    return `M ${x - offset[0]},${y - offset[1]}`
                  } else {
                    return `L ${x - offset[0]},${y - offset[1]}`
                  }
                })
                .join(' ')}
            />
          ))}
        </svg>
      </div>
    </Container>
  )
}

const Container = styled.div`
  display: flex;
  height: 100%;
  width: 100%;
  flex-direction: column;
  user-select: none;
  -webkit-user-select: none;

  .svg-wrapper {
    width: 100%;
    height: 100%;

    > svg {
      display: block;
      width: 100%;
      height: 100%;
      touch-action: none;
      user-select: none;
      -webkit-user-select: none;
    }
  }
`

function getXYFromMouseEvent(
  event: React.MouseEvent,
  [left, top]: [number, number],
  [offsetX, offsetY]: [number, number] = [0, 0]
): Point {
  return { x: event.clientX - left + offsetX, y: event.clientY - top + offsetY }
}

function getXYFromTouchEvent(
  event: TouchEvent,
  [left, top]: [number, number],
  touchType: TouchType | null,
  [offsetX, offsetY]: [number, number] = [0, 0]
): Point | null {
  const touch = getTouch(event, touchType)
  if (touch == null) return null
  const x = touch.clientX - left + offsetX
  const y = touch.clientY - top + offsetY
  return { x, y }
}

function getTouch(event: TouchEvent, touchType: TouchType | null): Touch | null {
  for (const changedTouch of Array.from(event.changedTouches)) {
    if (touchType == null || changedTouch.touchType === touchType) {
      return changedTouch
    }
  }
  return null
}

function compareTouchType(touch: Touch, touchType: TouchType): boolean {
  if (!('touchType' in touch) && touchType === 'direct') {
    return true
  }
  return touch.touchType === touchType
}

function getTouchType(palmRejectionEnabled: boolean): TouchType | null {
  return palmRejectionEnabled ? 'stylus' : null
}

// src/app/drawing-screen/drawing-screen.component.ts
import { Component, OnInit, HostListener, OnDestroy } from '@angular/core'
import { Path, Point } from '../picture.service'
import { Router, ActivatedRoute } from '@angular/router'
import { DrawingService } from '../drawing.service'
import { Subscription } from 'rxjs'
import { Tool } from '../tool-bar/tool-bar.component'
import { TitleAdapterService } from '../title-adapter.service'

@Component({
  selector: 'app-drawing-screen',
  templateUrl: './drawing-screen.component.html',
  styleUrls: ['./drawing-screen.component.scss']
})
export class DrawingScreenComponent implements OnInit, OnDestroy {
  pictureId: string | null = null

  selectedTool: Tool = 'pen'

  palmRejectionEnabled = false

  private subscription = new Subscription()

  constructor(
    private router: Router,
    private activatedRoute: ActivatedRoute,
    private drawingService: DrawingService,
    private titleAdapterService: TitleAdapterService
  ) {}

  ngOnInit() {
    this.drawingService.clean()

    const pictureId = this.activatedRoute.snapshot.params.pictureId
    if (typeof pictureId === 'string') {
      this.pictureId = pictureId
      this.drawingService.loadPicture(pictureId).then(() => {
        this.titleAdapterService.title.next(this.title)
      })
    } else {
      this.drawingService.init()
      this.titleAdapterService.title.next(this.title)
    }

    this.subscription.add(
      this.drawingService.onSave.subscribe(({ pictureId }) => {
        if (pictureId !== this.pictureId) {
          this.router.navigateByUrl(`/p/${pictureId}`)
        }
      })
    )
  }

  ngOnDestroy() {
    this.subscription.unsubscribe()
  }

  get title() {
    const { picture } = this.drawingService
    return picture != null ? picture.title : ''
  }

  set title(title: string) {
    this.drawingService.setTitle(title)
    this.titleAdapterService.title.next(title)
  }

  get paths() {
    const { picture } = this.drawingService
    return picture != null ? picture.paths : []
  }

  onMouseDown(event: MouseEvent) {
    switch (this.selectedTool) {
      case 'pen':
        this.drawingService.handlePenDown({
          color: '#000',
          width: 3,
          ...getXYFromMouseEvent(event)
        })
        break

      case 'eraser':
        this.drawingService.handleEraserDown(getXYFromMouseEvent(event))
        break
    }
  }

  onMouseMove(event: MouseEvent) {
    switch (this.selectedTool) {
      case 'pen':
        this.drawingService.handlePenMove(getXYFromMouseEvent(event))
        break

      case 'eraser':
        this.drawingService.handleEraserMove(getXYFromMouseEvent(event))
        break
    }
  }

  @HostListener('document:mouseup', ['$event'])
  onMouseUpGlobal(event: MouseEvent) {
    switch (this.selectedTool) {
      case 'pen':
        this.drawingService.handlePenUp()
        break

      case 'eraser':
        this.drawingService.handleEraserUp()
        break
    }
  }

  onTouchStart(event: TouchEvent) {
    switch (this.selectedTool) {
      case 'pen': {
        const xy = getXYFromTouchEvent(event, this.palmRejectionEnabled)
        if (xy == null) break
        event.preventDefault()
        this.drawingService.handlePenDown({
          color: '#000',
          width: 3,
          ...xy
        })
        break
      }

      case 'eraser': {
        const xy = getXYFromTouchEvent(event, this.palmRejectionEnabled)
        if (xy == null) break
        event.preventDefault()
        this.drawingService.handleEraserDown(xy)
        break
      }
    }
  }

  onTouchMove(event: TouchEvent) {
    switch (this.selectedTool) {
      case 'pen': {
        const xy = getXYFromTouchEvent(event, this.palmRejectionEnabled)
        if (xy == null) break
        event.preventDefault()
        this.drawingService.handlePenMove(xy)
        break
      }

      case 'eraser': {
        const xy = getXYFromTouchEvent(event, this.palmRejectionEnabled)
        if (xy == null) break
        event.preventDefault()
        this.drawingService.handleEraserMove(xy)
        break
      }
    }
  }

  onTouchEnd(event: TouchEvent) {
    switch (this.selectedTool) {
      case 'pen':
        if (getTouch(event, this.palmRejectionEnabled) != null) {
          event.preventDefault()
          this.drawingService.handlePenUp()
        }
        break

      case 'eraser':
        if (getTouch(event, this.palmRejectionEnabled) != null) {
          event.preventDefault()
          this.drawingService.handleEraserUp()
        }
        break
    }
  }

  getPathDescriptor(path: Path): string {
    return path.points
      .map(({ x, y }, i) => {
        if (i === 0) {
          return `M ${x},${y}`
        } else {
          return `L ${x},${y}`
        }
      })
      .join(' ')
  }
}

function getXYFromMouseEvent(event: MouseEvent): Point {
  return { x: event.offsetX, y: event.offsetY }
}

function getXYFromTouchEvent(event: TouchEvent, palmRejection: boolean): Point | null {
  const rect = (event.target as Element).closest('svg')!.getBoundingClientRect()
  const touch = getTouch(event, palmRejection)
  if (touch == null) return null
  const x = touch.clientX - window.pageXOffset - rect.left
  const y = touch.clientY - window.pageYOffset - rect.top
  return { x, y }
}

function getTouch(event: TouchEvent, palmRejection: boolean): Touch | null {
  if (!palmRejection) {
    return event.changedTouches[0]
  }

  for (const changedTouch of Array.from(event.changedTouches)) {
    if (changedTouch.touchType === 'stylus') {
      return changedTouch
    }
  }
  return null
}

<app-tool-bar
  [(title)]="title"
  [(selectedTool)]="selectedTool"
  [(palmRejectionEnabled)]="palmRejectionEnabled"
></app-tool-bar>
<div class="svg-wrapper">
  <svg
    (mousedown)="onMouseDown($event)"
    (mousemove)="onMouseMove($event)"
    (touchstart)="onTouchStart($event)"
    (touchmove)="onTouchMove($event)"
    (touchend)="onTouchEnd($event)"
  >
    <svg:path
      *ngFor="let path of paths"
      [attr.d]="getPathDescriptor(path)"
      fill="none"
      [attr.stroke]="path.color"
      [attr.stroke-width]="path.width"
    />
  </svg>
</div>
